version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: golfclub-mysql
    environment:
      MYSQL_DATABASE: golf_club_api
      MYSQL_ROOT_PASSWORD: fiqkir^.
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - golfclub-net

  api:
    build: .
    container_name: golfclub-api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://golfclub-mysql:3306/golf_club_api
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: fiqkir^.
    ports:
      - "8080:8080"
    networks:
      - golfclub-net

volumes:
  db_data:

networks:
  golfclub-net:
